// TR lang variables

tinyMCE.addToLang('media',{
title : 'Gömülü ortam ekle / düzenle',
desc : 'Gömülü ortam ekle / düzenle',
general : 'Genel',
advanced : 'Gelişmiş',
file : 'Dosya/Adres',
list : 'Liste',
size : 'Yönler',
preview : 'Önizleme',
constrain_proportions : 'Boyut kısıtlamaları',
type : 'Tür',
id : 'Kimlik',
name : 'İsim',
class_name : 'Sınıf',
vspace : 'D-Boşluk',
hspace : 'y-Boşluk',
play : 'Otomatik oynat',
loop : 'Döngü',
menu : 'Menüyü göster',
quality : 'Kalite',
scale : 'Ölçek',
align : 'Hiza',
salign : 'Hiza',
wmode : 'WMode',
bgcolor : 'Arkaalan',
base : 'Ana',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'Otomatik hedef',
cache : 'Ön Bellek',
hidden : 'Gizli',
controller : 'Denetim',
kioskmode : 'Köşk modu',
playeveryframe : 'Her çerçeveyi oynat',
targetcache : 'Hedef ön belleği',
correction : 'Düzeltme yok',
enablejavascript : 'JavaScript etkinleştir',
starttime : 'Başlangıç zamanı',
endtime : 'Bitiş zamanı',
href : 'Hedef',
qtsrcchokespeed : 'Sıkıştırma hız',
target : 'Hedef',
volume : 'Ses düzeyi',
autostart : 'Otomatik başlat',
enabled : 'Etkin',
fullscreen : 'Tam ekran',
invokeurls : 'Bağlantıları çalıştır',
mute : 'Sessiz',
stretchtofit : 'Ekrana genişlet',
windowlessvideo : 'Penceresiz vidyo',
balance : 'Denge',
baseurl : 'Ana adres',
captioningid : 'Başlık kimliği',
currentmarker : 'Varsayılan imleç',
currentposition : 'Varsayılan konum',
defaultframe : 'Varsayılan çerçeve',
playcount : 'Oynatma sayısı',
rate : 'Oran',
uimode : 'UI Modu',
flash_options : 'Flash seçenekleri',
qt_options : 'Quicktime seçenekleri',
wmp_options : 'Windows media player seçenekleri',
rmp_options : 'Real media player seçenekleri',
shockwave_options : 'Shockwave seçenekleri',
autogotourl : 'Adrese otomatik git',
center : 'Ortala',
imagestatus : 'Resim durumları',
maintainaspect : 'Gösteriyi devam ettir',
nojava : 'Java yok',
prefetch : 'Ön belleğe alma',
shuffle : 'Değiştirme',
console : 'İşletmen uçbirimi',
numloop : 'Döngü sayısı',
controls : 'Denetimler',
scriptcallbacks : 'Kod geri çağırmaları',
swstretchstyle : 'Genişletme biçemi',
swstretchhalign : 'Genişletme Y-Hizası',
swstretchvalign : 'Genişletme D-Hizası',
sound : 'Ses',
progress : 'İşlem',
qtsrc : 'QT Kaynağı',
qt_stream_warn : 'Gelişmiş sekmesi altında QT kaynağı eklenmiş olmalıdır..',
align_top : 'Üst',
align_right : 'Sağ',
align_bottom : 'Alt',
align_left : 'Sol',
align_center : 'Orta',
align_top_left : 'Sol üst',
align_top_right : 'Sağ üst',
align_bottom_left : 'Sol alt',
align_bottom_right : 'Sağ alt'
});