tinyMCE.addI18n('tr.advanced',{
style_select:"Biçemler",
font_size:"Yazıtipi Boyutu",
fontdefault:"Yazıtipi ailesi",
block:"Biçim",
paragraph:"Paragraf",
div:"Div",
address:"Adres",
pre:"Ön biçimli",
h1:"Başlık 1",
h2:"Başlık 2",
h3:"Başlık 3",
h4:"Başlık 4",
h5:"Başlık 5",
h6:"Başlık 6",
blockquote:"Alıntı",
code:"Kod",
samp:"Kod örneği",
dt:"Tanım terimi ",
dd:"Tanım açıklaması",
bold_desc:"Kalın (Ctrl+B)",
italic_desc:"İtalik (Ctrl+I)",
underline_desc:"Altı Çizgili (Ctrl+U)",
striketrough_desc:"Ortası Çizgili",
justifyleft_desc:"Sola hizala",
justifycenter_desc:"Ortala",
justifyright_desc:"Sağa hizala",
justifyfull_desc:"Yasla",
bullist_desc:"Madde işaretleri",
numlist_desc:"Numaralandırma",
outdent_desc:"Girintiyi azalt",
indent_desc:"Girintiyi artır",
undo_desc:"Geri al (Ctrl+Z)",
redo_desc:"Yenile (Ctrl+Y)",
link_desc:"Bağlantı ekle/düzenle",
unlink_desc:"Bağlantıyı kaldır",
image_desc:"Resim ekle/düzenle",
cleanup_desc:"Dağınık kodu temizle",
code_desc:"HTML Kaynağını Düzenle",
sub_desc:"Altsimge",
sup_desc:"Üstsimge",
hr_desc:"Yatay çizgi ekle",
removeformat_desc:"Biçimlemeyi kaldır",
custom1_desc:"Özel açıklamanız",
forecolor_desc:"Metin rengini seçin",
backcolor_desc:"Arkaalan rengini seçin",
charmap_desc:"Özel karakter ekle",
visualaid_desc:"Yönergeleri ve görünmez öğeleri aç/kapat",
anchor_desc:"İç bağlantı ekle/düzenle",
cut_desc:"Kes",
copy_desc:"Kopyala",
paste_desc:"Yapıştır",
image_props_desc:"Resim özellikleri",
newdocument_desc:"Yeni belge",
help_desc:"Yardım",
blockquote_desc:"Alıntı",
clipboard_msg:"Mozilla ve Firefox için kopyalama/kesme/yapıştırma işlemleri yürütülemez.\r\nBu durum hakkında daha fazla bilgi almak ister misiniz?",
path:"Yol",
newdocument:"Tüm içeriği temizlemek istediğinizden emin misiniz?",
toolbar_focus:"Araç düğmelerine atla - Alt+Q, Düzenleyiciye atla - Alt-Z, Öğe yoluna atla - Alt-X",
more_colors:"Daha fazla renk"
});