tinyMCE.addI18n('tr.advanced_dlg',{
about_title:"TinyMCE Hakkında",
about_general:"Hakkında",
about_help:"Yardım",
about_license:"Lisans",
about_plugins:"Uyumlu Ekler",
about_plugin:"Uyumlu Ek",
about_author:"Yazar",
about_version:"Sürüm",
about_loaded:"Yüklü uyumlu ekler",
anchor_title:"İç bağlantı ekle/düzenle",
anchor_name:"İç bağlantı adı",
code_title:"HTML Kaynağı Düzenleyicisi",
code_wordwrap:"Kelime kaydırma",
colorpicker_title:"Bir renk seçiniz",
colorpicker_picker_tab:"Seçici",
colorpicker_picker_title:"Renk seçici",
colorpicker_palette_tab:"Palet",
colorpicker_palette_title:"Palet renkleri",
colorpicker_named_tab:"İsimlendirilmiş",
colorpicker_named_title:"İsimlendirilmiş renkler",
colorpicker_color:"Renk:",
colorpicker_name:"İsim:",
charmap_title:"Özel karakter seçiniz",
image_title:"Resim ekle/düzenle",
image_src:"Resim adresi",
image_alt:"Resim açıklaması",
image_list:"Resim listesi",
image_border:"Kenarlık",
image_dimensions:"Boyutlar",
image_vspace:"Dikey boşluk",
image_hspace:"Yatay boşluk",
image_align:"Hizalama",
image_align_baseline:"Anasatırda",
image_align_top:"Üstte",
image_align_middle:"Ortada",
image_align_bottom:"Altta",
image_align_texttop:"Metnin üstünde",
image_align_textbottom:"Metnin altında",
image_align_left:"Solda",
image_align_right:"Sağda",
link_title:"Bağlantı ekle/düzenle",
link_url:"Adres",
link_target:"Hedef",
link_target_same:"Aynı pencerede aç",
link_target_blank:"Yeni pencerede aç",
link_titlefield:"Başlık",
link_is_email:"Girdiğiniz adres, bir e-Posta adresi gibi görünmektedir. mailto: ön ekini eklemek ister misiniz?",
link_is_external:"Girdiğiniz adres harici bir bağlantı gibi görünmektedir. http:// ön ekini eklemek ister misiniz?",
link_list:"Bağlantı listesi"
});