// TR lang variables

tinyMCE.addToLang('table',{
general_tab : 'Genel',
advanced_tab : 'Gelişmiş',
general_props : 'Genel özellikler',
advanced_props : 'Gelişmiş özellikler',
desc : 'Yeni tablo ekler',
row_before_desc : 'Önüne satır ekle',
row_after_desc : 'Arkasına satır ekle',
delete_row_desc : 'Satırı sil',
col_before_desc : 'Önüne kolon ekle',
col_after_desc : 'Önüne kolon ekle',
delete_col_desc : 'Kolonu sil',
rowtype : 'Tablo parçasındaki satır',
title : 'Tablo ekle/düzenle',
width : 'Genişlik',
height : 'Yükseklik',
cols : 'Kolonlar',
rows : 'Satırlar',
cellspacing : 'Hücre boşluğu',
cellpadding : 'Hücre dolgusu',
border : 'Kenarlık',
align : 'Hizalama',
align_default : 'Varsayılan',
align_left : 'Sol',
align_right : 'Sağ',
align_middle : 'Orta',
row_title : 'Satır özellikleri',
cell_title : 'Hücre özellikleri',
cell_type : 'Hücre türü',
row_desc : 'Satır özellikleri',
cell_desc : 'Hücre özellikleri',
valign : 'Dikey hizalama',
align_top : 'Üst',
align_bottom : 'Alt',
props_desc : 'Tablo özellikleri',
bordercolor : 'Kenarlık rengi',
bgcolor : 'Arkaalan rengi',
merge_cells_title : 'Hücreleri birleştir',
split_cells_desc : 'Birleştirilmiş hücreleri ayır',
merge_cells_desc : 'Hüvreleri birleştir',
cut_row_desc : 'Satırı kes',
copy_row_desc : 'Satırı kopyala',
paste_row_before_desc : 'Önüne satır yapıştır',
paste_row_after_desc : 'Arkasına satır yapıştır',
id : 'Kimlik',
style: 'Biçem',
langdir : 'Dil yönü',
langcode : 'Dil kodu',
mime : 'Hedef MIME türü',
ltr : 'Soldan sağa',
rtl : 'Sağdan sola',
bgimage : 'Arkaalan resmi',
summary : 'Özet',
td : "Bilgi",
th : "Başlık",
cell_cell : 'Geçerli hücreyi güncelle',
cell_row : 'Satırdaki tüm hücreleri güncelle',
cell_all : 'Tablodaki tüm hücreleri güncelle',
row_row : 'Geçerli satırı güncelle',
row_odd : 'Tek satırları güncelle',
row_even : 'Çift satırları güncelle',
row_all : 'Tüm satırları güncelle',
thead : 'Tablo Başlığı',
tbody : 'Tablo Gövdesi',
tfoot : 'Tablo Altı',
del : 'Tabloyu sil',
scope : 'Kapsam',
row : 'Satır',
col : 'Kolon',
rowgroup : 'Satır Grubu',
colgroup : 'Kolon Grubu',
col_limit : 'İzin verilen en fazla kolon sayısına ulaştınız: {$cols}.',
row_limit : 'İzin verilen en fazla satır sayısına ulaştınız: {$rows}.',
cell_limit : 'İzin verilen en fazla hücre sayısına ulaştınız: {$cells}.',
missing_scope: 'Tablonun üst hücresi için kapsam belirtmeden devam etmek istediğinize emin misiniz?',
caption : 'Tablo başlığı'
});
