tinyMCE.addI18n('tr.table_dlg',{
general_tab:"Genel",
advanced_tab:"Gelişmiş",
general_props:"Genel özellikler",
advanced_props:"Gelişmiş özellikler",
rowtype:"Tablo parçasındaki satır",
title:"Tablo ekle/düzenle",
width:"Genişlik",
height:"Yükseklik",
cols:"Kolonlar",
rows:"Satırlar",
cellspacing:"Hücre boşluğu",
cellpadding:"Hücre dolgusu",
border:"Kenarlık",
align:"Hizalama",
align_default:"Varsayılan",
align_left:"Sol",
align_right:"Sağ",
align_middle:"Orta",
row_title:"Satır özellikleri",
cell_title:"Hücre özellikleri",
cell_type:"Hücre türü",
valign:"Dikey hizalama",
align_top:"Üst",
align_bottom:"Alt",
bordercolor:"Kenarlık rengi",
bgcolor:"Arkaalan rengi",
merge_cells_title:"Hücreleri birleştir",
id:"Kimlik",
style:"Biçem",
langdir:"Dil yönü",
langcode:"Dil kodu",
mime:"Hedef MIME türü",
ltr:"Soldan sağa",
rtl:"Sağdan sola",
bgimage:"Arkaalan resmi",
summary:"Özet",
td:"Bilgi",
th:"Başlık",
cell_cell:"Geçerli hücreyi güncelle",
cell_row:"Satırdaki tüm hücreleri güncelle",
cell_all:"Tablodaki tüm hücreleri güncelle",
row_row:"Geçerli satırı güncelle",
row_odd:"Tek satırları güncelle",
row_even:"Çift satırları güncelle",
row_all:"Tüm satırları güncelle",
thead:"Tablo Başlığı",
tbody:"Tablo Gövdesi",
tfoot:"Tablo Altı",
scope:"Kapsam",
rowgroup:"Satır Grubu",
colgroup:"Kolon Grubu",
col_limit:"İzin verilen en fazla kolon sayısına ulaştınız: {$cols}.",
row_limit:"İzin verilen en fazla satır sayısına ulaştınız: {$rows}.",
cell_limit:"İzin verilen en fazla hücre sayısına ulaştınız: {$cells}.",
missing_scope:"Tablonun üst hücresi için kapsam belirtmeden devam etmek istediğinize emin misiniz?",
caption:"Tablo başlığı",
frame:"Çerçeve",
frame_none:"yok",
frame_groups:"gruplar",
frame_rows:"satırlar",
frame_cols:"kolonlar",
frame_all:"tümü",
rules:"Kurallar",
rules_void:"boş",
rules_above:"yukarı",
rules_below:"aşağı",
rules_hsides:"yyanlar",
rules_lhs:"sol",
rules_rhs:"sağ",
rules_vsides:"dyanlar",
rules_box:"kutu",
rules_border:"kenarlık"
});