tinyMCE.addI18n('tr.advimage_dlg',{
tab_general:"Genel",
tab_appearance:"Görünüm",
tab_advanced:"Gelişmiş",
general:"Genel",
title:"Başlık",
preview:"Önizleme",
constrain_proportions:"Boyut kısıtlamaları",
langdir:"Dil yönü",
langcode:"Dil kodu",
long_desc:"Uzun açıklama bağlantısı",
style:"Biçem",
classes:"Sınıflar",
ltr:"Soldan Sağa",
rtl:"Sağdan Sola",
id:"Kimlik",
map:"Resim haritalama",
swap_image:"Alternatif",
alt_image:"Alternatif resim",
mouseover:"fare imleci üstte ise",
mouseout:"fare imleci dışarda ise",
misc:"Diğerleri",
example_img:"Görünüm önizleme resim",
missing_alt:"Herhangi bir resim açıklaması eklemeden devam etmek istediğinizi emin misiniz?",
dialog_title:"Resim ekle/düzenle",
src:"Resim adresi",
alt:"Resim açıklaması",
list:"Resim listesi",
border:"Kenarlık",
dimensions:"Boyutlar",
vspace:"Dikey boşluk",
hspace:"Yatay boşluk",
align:"Hizalama",
align_baseline:"Anasatırda",
align_top:"Üstte",
align_middle:"Ortada",
align_bottom:"Altta",
align_texttop:"Metnin üstünde",
align_textbottom:"Metnin altında",
align_left:"Solda",
align_right:"Sağda",
image_list:"Resim listesi"
});