tinyMCE.addI18n('tr.xhtmlxtras_dlg',{
attribute_label_title:"Başlık",
attribute_label_id:"Kimlik",
attribute_label_class:"Sınıf",
attribute_label_style:"Biçem",
attribute_label_cite:"Aktarma",
attribute_label_datetime:"Tarih/Zaman",
attribute_label_langdir:"Metin Yönü",
attribute_option_ltr:"Soldan sağa",
attribute_option_rtl:"Sağdan sola",
attribute_label_langcode:"Dil",
attribute_label_tabindex:"Sekme Sırası",
attribute_label_accesskey:"Erişim Tuşu",
attribute_events_tab:"Olaylar",
attribute_attrib_tab:"Öznitelikler",
general_tab:"Genel",
attrib_tab:"Öznitelikler",
events_tab:"Olaylar",
fieldset_general_tab:"Genel Ayarlar",
fieldset_attrib_tab:"Öğe Öznitelikleri",
fieldset_events_tab:"Öğe Olayları",
title_ins_element:"Ekleme Öğesi",
title_del_element:"Silme Öğesi",
title_acronym_element:"Akronim Öğesi",
title_abbr_element:"Kısaltma Öğesi",
title_cite_element:"Alıntı Öğesi",
remove:"Kaldır",
insert_date:"Güncel tarihi/zamanı ekle",
option_ltr:"Soldan sağa",
option_rtl:"Sağdan sola",
attribs_title:"Öznitelik ekle/düzenle"
});