// TR lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Genel',
popup_tab : 'Açılır Pencere',
events_tab : 'Olaylar',
advanced_tab : 'Gelişmiş',
general_props : 'Genel özellikler',
popup_props : 'Açılır pencere özellikleri',
event_props : 'Olaylar',
advanced_props : 'Gelişmiş özellikler',
popup_opts : 'Seçenekler',
anchor_names : 'İç Bağlantılar',
target_same : 'Bu pencerede/çerçevede aç',
target_parent : 'Ana pencerede/çerçevede aç',
target_top : 'Üst çerçevede aç (tüm çerçeveler değişir)',
target_blank : 'Yeni pencerede aç',
popup : 'Javascript açılır pencere',
popup_url : 'Açılır pencere adresi',
popup_name : 'Pencere ismi',
popup_return : '\'return false\' ekle',
popup_scrollbars : 'Kaydırma çubuklarını göster',
popup_statusbar : 'Durum çubuğunu göster',
popup_toolbar : 'Araççubuklarını göster',
popup_menubar : 'Menüyü göster',
popup_location : 'Konumu göster',
popup_resizable : 'Pencereyi boyutlandırılabilir yap',
popup_dependent : 'Bağımlı (sadece Mozilla/Firefox)',
popup_size : 'Boyut',
popup_position : 'Konum (X/Y)',
id : 'Kimlik',
style: 'Biçem',
classes : 'Sınıflar',
target_name : 'Hedef ismi',
langdir : 'Dil yönü',
target_langcode : 'Hedef dil',
langcode : 'Dil kodu',
encoding : 'Hedef karakter kodlaması',
mime : 'Hedef MIME türü',
rel : 'Hedefle ilişkili sayfa',
rev : 'Sayfa ile ilişkili hedef',
tabindex : 'Sekme sırası',
accesskey : 'Erişim tuşu',
ltr : 'Soldan sağa',
rtl : 'Sağdan sola'
});