// TR lang variables

tinyMCE.addToLang('style',{
title : 'CSS Biçemi Düzenle',
styleinfo_desc : 'CSS Biçemi Düzenle',
apply : 'Uygula',
text_tab : 'Metin',
background_tab : 'Arkaalan',
block_tab : 'Öbek',
box_tab : 'Kutu',
border_tab : 'Kenarlık',
list_tab : 'Liste',
positioning_tab : 'Konumlandırma',
text_props : 'Metin',
text_font : 'Yazıtipi',
text_size : 'Boyut',
text_weight : 'Genişlik',
text_style : 'Biçem',
text_variant : 'Değişke',
text_lineheight : 'Satır yüksekliği',
text_case : 'Büyük/küçük harf',
text_color : 'Renk',
text_decoration : 'Dekorasyon',
text_overline : 'Üstü çizgili',
text_underline : 'Altı çizgili',
text_striketrough : 'Ortası çizgili',
text_blink : 'Yansön',
text_none : 'yok',
background_color : 'Arkaalan rengi',
background_image : 'Arkaalan resmi',
background_repeat : 'Tekrar',
background_attachment : 'Ek',
background_hpos : 'Yatay konum',
background_vpos : 'Dikey konum',
block_wordspacing : 'Sözcük boşluğu',
block_letterspacing : 'Harf boşluğu',
block_vertical_alignment : 'Dikey hizalama',
block_text_align : 'Metin hizalama',
block_text_indent : 'Metin girintisi',
block_whitespace : 'Boşluk',
block_display : 'Görüntüle',
box_width : 'Genişlik',
box_height : 'Yükseklik',
box_float : 'Kaydırma',
box_clear : 'Temiz',
padding : 'Dolgu',
same : 'Tümü için aynı',
top : 'Üst',
right : 'Sağ',
bottom : 'Alt',
left : 'Sol',
margin : 'Kenar Boşluğu',
style : 'Biçem',
width : 'Genişlik',
height : 'Yükseklik',
color : 'Renk',
list_type : 'Tür',
bullet_image : 'Madde imi resmi',
position : 'Konum',
positioning_type : 'Tür',
visibility : 'Görünürlük',
zindex : 'z-dizini',
overflow : 'Taşma',
placement : 'Yerleştirme',
clip : 'Küçük resim'
});
