tinyMCE.addI18n('tr.fullpage_dlg',{
title:"Belge özellikleri",
meta_tab:"Genel",
appearance_tab:"Görünüm",
advanced_tab:"Gelişmiş",
meta_props:"Tanımlayıcı bilgi",
langprops:"Dil ve kodlama",
meta_title:"Başlık",
meta_keywords:"Anahtar sözcükler",
meta_description:"Açıklama",
meta_robots:"Robotlar",
doctypes:"Belge türü",
langcode:"Dil kodu",
langdir:"Dil yönü",
ltr:"Soldan sağa",
rtl:"Sağdan sola",
xml_pi:"XML bildirimi",
encoding:"Karakter kodlaması",
appearance_bgprops:"Arkaalan özellikleri",
appearance_marginprops:"Gövde kenar boşlukları",
appearance_linkprops:"Bağlantı renkleri",
appearance_textprops:"Metin özellikleri",
bgcolor:"Arkaalan rengi",
bgimage:"Arkaalan resmi",
left_margin:"Sol kenar boşluğu",
right_margin:"Sağ kenar boşluğu",
top_margin:"Üst kenar boşluğu",
bottom_margin:"Alt kenar boşluğu",
text_color:"Metin rengi",
font_size:"Yazıtipi boyutu",
font_face:"Yazıtipi yüzü",
link_color:"Bağlantı rengi",
hover_color:"İmleç üstteyken renk",
visited_color:"Ziyaret edilmiş bağlantı rengi",
active_color:"Etkin bağlantı rengi",
textcolor:"Renk",
fontsize:"Yazıtipi boyutu",
fontface:"Yazıtipi ailesi",
meta_index_follow:"Bağlantıları indisle ve takip et",
meta_index_nofollow:"Bağlantıları indisle ve takip etme",
meta_noindex_follow:"Bağlantıları indisleme ama takip et",
meta_noindex_nofollow:"Bağlantıları indisleme ve takip etme",
appearance_style:"Biçem sayfası ve biçem özellikleri",
stylesheet:"Biçem sayfası",
style:"Biçem",
author:"Yazar",
copyright:"Telif hakkı",
add:"Yeni öğe ekle",
remove:"Seçili öğeyi kaldır",
moveup:"Seçili öğeyi yukarı taşı",
movedown:"Seçili öğeyi aşağı taşı",
head_elements:"Baş öğeler",
info:"Bilgi",
add_title:"Başlık öğesi",
add_meta:"Tanımlama öğesi",
add_script:"Kod öğesi",
add_style:"Biçim öğesi",
add_link:"Bağlantı öğesi",
add_base:"Ana öğe",
add_comment:"Yorum ağı",
title_element:"Başlık öğesi",
script_element:"Kod öğesi",
style_element:"Biçem öğesi",
base_element:"Ana öğe",
link_element:"Bağlantı öğesi",
meta_element:"Tanımlayıcı öğe",
comment_element:"Yorum",
src:"Kaynak",
language:"Dil",
href:"Hedef",
target:"Hedef",
type:"Tür",
charset:"Karakter Kümesi",
defer:"Erteleme",
media:"Ortam",
properties:"Özellikler",
name:"İsim",
value:"Değer",
content:"İçerik",
rel:"Göreli",
rev:"Sür",
hreflang:"Hedef dili",
general_props:"Genel",
advanced_props:"Gelişmiş"
});